### ISSUE TITLE
KDTree error when k=1

### ISSUE THREAD

**Issue by rasmi** [pysal/pysal#1006]
- Platform information:
`posix darwin`
- Python version: 
`3.6.2`
- SciPy version:
`0.19.1`
- NumPy version:
`1.13.3`
---

The following code 
```
import pysal as ps
import numpy as np

np.random.seed(42)
lngs = np.random.uniform(-180, 180, (100, 1))
lats = np.random.uniform(-90, 90, (100, 1))
coords = np.hstack((lngs, lats))

tree = ps.cg.KDTree(coords, distance_metric='Arc', radius=ps.cg.RADIUS_EARTH_KM)

print(tree.query((90, 0)))
```
Results in the following error:
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    print(tree.query((90, 0)))
  File "pythonenv/lib/python3.6/site-packages/pysal/cg/kdtree.py", line 161, in query
    dims = len(d.shape)
AttributeError: 'float' object has no attribute 'shape'
```
The issue is specifically [here](https://github.com/pysal/pysal/blob/8a487c10668496c68fd7f834c369c50b1506535c/pysal/cg/kdtree.py#L161). It seems that when `k=1` (the default argument), `tree.query` in scikit-learn returns a tuple of `(distance <float>, index <int>)` , so that line `dims = len(d.shape)` is trying to take the shape of a float. When `k>1`, the tuple is`(distance <np.array>, index <np.array>)`, which allows the `.shape` call to work.

**Comment by weikang9009** [comment]
Thank you for reporting the issue. I can replicate the error on 
* Platform: macOS High Sierra 10.13.1
* Python version: 3.6.2
* SciPy version: 0.19.1
* NumPy version:1.13.3
while I do not encounter any error if using SciPy is updated to version 1.0.0.

When using **SciPy 1.0.0**, the method ```tree.query``` in scipy returns a tuple of (distance <numpy.float64>, index <numpy.int6>) instead of (distance <float>, index <int>). Since ```d``` is of type **numpy.float64**, ```d.shape``` will work:
<img width="381" alt="d42b242c-4152-452b-8745-99841d31c3d8" src="https://user-images.githubusercontent.com/7359284/33038809-af817382-cdea-11e7-8a1a-ba2a2a31df16.png">

Could you please trying running your python code after updating scipy to 1.0.0 to see whether the same error occurs?
