### ISSUE TITLE
Pysal 23.1 and Numpy 1.23.5

### ISSUE THREAD

**Issue by bermoda04** [pysal/pysal#1272]
With these 2 packages, import gives error ImportError: cannot import name 'asscalar' from 'numpy'

A quick conversation with chatgpt says that "The latest release of PySAL (as of my knowledge cutoff in September 2021) is version 2.4.0, and it is compatible with NumPy 1.20 or later." So with newer versions of pysal, this might work with numpy 1.23. However, it seems like I cannot install a newer pysal package no matter what conda install or conda update I input on my cmd.

**Comment by sjsrey** [comment]
Thanks for reporting this.

Could you provide a [minimum working example](https://leanprover-community.github.io/mwe.html#:~:text=Formal%20Definition,include%20unnecessary%20details%20(minimal).) so that we might better investigate this issue?

It seems `asscalar` has been deprecated in `numpy` since [1.16](https://numpy.org/doc/1.21/reference/generated/numpy.asscalar.html).

**Comment by bermoda04** [comment]
It seems like I cannot provide the code snippet as I already removed it from my jupyter notebook.
